source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'
use_frameworks!

target 'WKRPT401' do
    pod 'Alamofire', '~> 4.0'
    pod 'wkrpt401-grpc', :path => '.'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
